### PR TITLE
[NO-JIRA] Unit tests.

### PR DESCRIPTION
**Pull request by ogryniuk**
Complete a unit test for the class NativeResourceLoader

### CODE REVIEW

**Comment by yildiz-online** [comment]
The tests are failing because the file is not found, you first have to add files in the sources (in src/test/resources) both dll & so

Then it should be fine.

**Comment by yildiz-online** [comment]
Still failing, files are missing.

**Comment by ogryniuk** [comment]
This is the content of the folder src/test/resources

https://www.dropbox.com/s/hxdoly7sx39oca1/Contenu%20du%20src%20test%20resources.jpg?dl=0

**Comment by yildiz-online** [comment]
Check with git status if the required files are correclty included, i do not see them in the commit and the CI does not pass (null pointer exception)

**Comment by yildiz-online** [comment]
Merged in bitbucket.

**Pull request closed without merging**
